# This file is for plugin metadata ONLY.
# It is NOT visible to the user and should NOT contain settings.

name: WorldStream
version: 0.5.61
description: Use Minecraft as a voxel-based level editor!
authors: [DerekElam, AustinBaird]
main: edu.utc.bkf926.WorldStream.WorldStream
commands:
  worldstream:
    description: Access WorldStream server status.
    usage: "Usage: /worldstream [info, clients]"